POST http://localhost:5154/api/salaries
Content-Type: application/json

{
  "country": "Sri Lanka",
  "company": "Dialog",
  "role": "Software Engineer",
  "experienceLevel": "Mid",
  "salaryAmount": 350000,
  "currency": "LKR",
  "anonymize": true
}