kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgrescommunitydb-storage
  namespace: techsalary-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
