kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-storage-submissions
  namespace: techsalary
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi