apiVersion: v1
kind: Secret
metadata:
  name: postgresidentitydb-secret
  namespace: techsalary
type: Opaque
stringData:
  POSTGRES_DB: identitydb
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: ad123
---
apiVersion: v1
kind: Secret
metadata:
  name: postgressubmissionsdb-secret
  namespace: techsalary
type: Opaque
stringData:
  POSTGRES_DB: submissionsdb
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: ad123
---
apiVersion: v1
kind: Secret
metadata:
  name: postgrescommunitydb-secret
  namespace: techsalary
type: Opaque
stringData:
  POSTGRES_DB: communitydb
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: ad123
