apiVersion: v1
kind: Secret
metadata:
  name: postgres-identity-secret
  namespace: techsalary-data
type: Opaque
stringData:
  POSTGRES_DB: identitydb
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: ad123
