apiVersion: v1
kind: Secret
metadata:
  name: postgres-community-secret
  namespace: techsalary-data
type: Opaque
stringData:
  POSTGRES_DB: communitydb
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: ad123
