apiVersion: v1
kind: Secret
metadata:
  name: postgres-submissions-secret
  namespace: techsalary-data
type: Opaque
stringData:
  POSTGRES_DB: submissionsdb
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: ad123
