apiVersion: v1
kind: ConfigMap
metadata:
  name: identity-init-script
  namespace: techsalary-data
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS "Users" (
        "UserId" UUID PRIMARY KEY,
        "FirstName" VARCHAR(100) NOT NULL,
        "LastName" VARCHAR(100) NOT NULL,
        "Email" VARCHAR(256) NOT NULL,
        "PasswordHash" TEXT NOT NULL,
        "Role" VARCHAR(50) NOT NULL DEFAULT 'User',
        "IsActive" BOOLEAN NOT NULL,
        "IsEmailVerified" BOOLEAN NOT NULL,
        "CreatedAt" TIMESTAMP WITH TIME ZONE NOT NULL,
        "UpdatedAt" TIMESTAMP WITH TIME ZONE NULL,
        "LastLoginAt" TIMESTAMP WITH TIME ZONE NULL
    );

    CREATE UNIQUE INDEX IF NOT EXISTS "IX_Users_Email"
    ON "Users" ("Email");

    CREATE TABLE IF NOT EXISTS "AuthRefreshTokens" (
        "RefreshTokenId" UUID PRIMARY KEY,
        "UserId" UUID NOT NULL,
        "Token" TEXT NOT NULL,
        "ExpiresAt" TIMESTAMP WITH TIME ZONE NOT NULL,
        "CreatedAt" TIMESTAMP WITH TIME ZONE NOT NULL,
        "IsRevoked" BOOLEAN NOT NULL,
        CONSTRAINT "FK_AuthRefreshTokens_Users_UserId"
            FOREIGN KEY ("UserId")
            REFERENCES "Users" ("UserId")
            ON DELETE CASCADE
    );

    CREATE INDEX IF NOT EXISTS "IX_AuthRefreshTokens_UserId"
    ON "AuthRefreshTokens" ("UserId");
