apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresidentitydb
  namespace: techsalary-data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresidentitydb
  template:
    metadata:
      labels:
        app: postgresidentitydb
    spec:
      containers:
        - name: postgresidentitydb
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_IDENTITY_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: postgresidentitydb-data
              mountPath: /var/lib/postgresql/data
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d/
      volumes:
        - name: postgresidentitydb-data
          persistentVolumeClaim:
            claimName: postgresidentitydb-storage
        - name: init-script
          configMap:
            name: postgres-init-identity-script
