apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-submissions
  namespace: techsalary-data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-submissions
  template:
    metadata:
      labels:
        app: postgres-submissions
    spec:
      containers:
        - name: postgres-submissions
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-submissions-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-submissions-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-submissions-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: postgres-submissions-data
              mountPath: /var/lib/postgresql/data
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d/
      volumes:
        - name: postgres-submissions-data
          persistentVolumeClaim:
            claimName: postgres-submissions-storage
        - name: init-script
          configMap:
            name: postgres-init-submissions-script
