apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-community
  namespace: techsalary-data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-community
  template:
    metadata:
      labels:
        app: postgres-community
    spec:
      containers:
        - name: postgres-community
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-community-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-community-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-community-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: postgres-community-data
              mountPath: /var/lib/postgresql/data
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d/
      volumes:
        - name: postgres-community-data
          persistentVolumeClaim:
            claimName: postgres-community-storage
        - name: init-script
          configMap:
            name: postgres-init-community-script
