apiVersion: v1
kind: Service
metadata:
  name: postgrescommunitydb
  namespace: techsalary
spec:
  selector:
    app: postgrescommunitydb
  ports:
    - port: 5435
      targetPort: 5432
  type: ClusterIP