apiVersion: v1
kind: Service
metadata:
  name: postgresCommunityDb
  namespace: techsalary
spec:
  selector:
    app: postgresCommunityDb
  ports:
    - port: 5435
      targetPort: 5432
  type: ClusterIP