apiVersion: v1
kind: Service
metadata:
  name: postgresIdentityDb
  namespace: techsalary
spec:
  selector:
    app: postgresIdentityDb
  ports:
    - port: 5433
      targetPort: 5432
  type: ClusterIP