apiVersion: v1
kind: Service
metadata:
  name: postgres-submissions
  namespace: techsalary-data
spec:
  selector:
    app: postgres-submissions
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
