apiVersion: v1
kind: Service
metadata:
  name: salarysubmissionapi
  namespace: techsalary
spec:
  selector:
    app: salarysubmissionapi
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP