apiVersion: v1
kind: Service
metadata:
  name: postgresSubmissionsDb
  namespace: techsalary
spec:
  selector:
    app: postgresSubmissionsDb
  ports:
    - port: 5434
      targetPort: 5432
  type: ClusterIP