apiVersion: v1
kind: Service
metadata:
  name: postgressubmissionsdb
  namespace: techsalary
spec:
  selector:
    app: postgressubmissionsdb
  ports:
    - port: 5434
      targetPort: 5432
  type: ClusterIP